name: Static Application Security Check for GoLang
description: |
  Runs a static Application Security Check, via semgrep against your project.
  The report will be stored as an artifact called `sast-report.json`.
  
  All internal dependencies are cloned via HTTPS, instead of Git-SSH.
author: 'Tim Rutte <info@timrutte.de>'
inputs:
  SEMGREP_RULES:
    description: "Ruleset for semgrep"
    default: "p/golang"
    required: true
  SEMGREP_VERSION:
    description: "Semgrep version"
    default: ">=0.123.0"
    required: true

  CI_JOB_TOKEN:
    description: "Token used for authentication against CI_SERVER_HOST"
    default: "${{ github.token }}"
    required: true
  CI_SERVER_HOST:
    description: "Server host, e.g. github.com"
    default: "github.com"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set git insteadOf rules
      shell: bash
      run: |
        git config --global --add url."https://${{ inputs.CI_JOB_TOKEN }}@${{ inputs.CI_SERVER_HOST }}/".insteadOf "ssh://git@${{ inputs.CI_SERVER_HOST }}/"
        git config --global --add url."https://${{ inputs.CI_JOB_TOKEN }}@${{ inputs.CI_SERVER_HOST }}/".insteadOf "ssh://${{ inputs.CI_SERVER_HOST }}/"
        git config --global --add url."https://${{ inputs.CI_JOB_TOKEN }}@${{ inputs.CI_SERVER_HOST }}/".insteadOf "git://${{ inputs.CI_SERVER_HOST }}/"
        git config --global --add url."https://${{ inputs.CI_JOB_TOKEN }}@${{ inputs.CI_SERVER_HOST }}/".insteadOf "https://${{ inputs.CI_SERVER_HOST }}/"

    # @TODO: Replace with github action from semgrep
    - uses: actions/setup-python@v1
    - name: Run semgrep ci
      shell: bash
      run: |
        export SEMGREP_RULES="${{ inputs.SEMGREP_RULES }}"
        python3 -m pip install 'semgrep${{ inputs.SEMGREP_VERSION }}'
        semgrep ci > sast-report.json || true

    - name: Remove git insteadOf rules
      shell: bash
      run: git config --global --remove-section url."https://${{ inputs.CI_JOB_TOKEN }}@${{ inputs.CI_SERVER_HOST }}/"

    - uses: actions/upload-artifact@v3  
      if: success() || failure()    
      with:
        name: artifact-results
        path: |
          sast-report.json
