name: Deploy to k8s via manifest file
description: |
  Apply your `DEPLOYMENT_FILE` on a k8s-Cluster, with `kubectl apply`. Currently only AWS k8s cluster supported.
  
  Before the deploy process the Job will call the `pre_deployment.sh` script, located in the `CICD_DIR` with `PARAM_PRESCRIPT`. If the file not exist, nothing will happen.
  After the deploy process the Job will call the `post_deployment.sh` script, located in the `CICD_DIR` with `POST_PRESCRIPT`. If the file not exist, nothing will happen.
author: 'Tim Rutte <info@timrutte.de>'
inputs:
  CLUSTER_NAME:
    description: "Name of the cluster that should be used."
    required: true
  DEPLOYMENT_FILE:
    description: "Path to deployment file"
    required: true

  AWS_ACCESS_KEY_ID:
    description: "AWS access key id"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret access key"
    required: true
  AWS_DEFAULT_REGION:
    description: "Default AWS region"
    default: "eu-west-1"
    required: true

  CICD_DIR:
    description: "Default CI/CD directory, used for special files like pre_deployment-scripts"
    default: ".cicd"
    required: false
  PARAM_PRESCRIPT:
    description: "Parameter for pre_deployment.sh"
    required: false
  PARAM_POSTSCRIPT:
    description: "Parameter for post_deployment.sh"
    required: false
  
runs:
  using: "composite"
  steps:
    - name: "Install kubectl"
      uses: azure/setup-kubectl@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

    - name: "Set kube config"
      shell: bash
      run: |
        aws eks update-kubeconfig --name "${{ inputs.CLUSTER_NAME }}" --kubeconfig "${{ runner.temp }}/.kube/kubeconfig_${{ github.job }}"

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: "Run pre script"
      shell: bash
      run: if test -f "${{ inputs.CICD_DIR }}/pre_deployment.sh"; then bash "${{ inputs.CICD_DIR }}/pre_deployment.sh" ${{ inputs.PARAM_PRESCRIPT }}; fi


    - name: "Deploy via kustomize"
      shell: bash
      run: |
        kubectl --kubeconfig "${{ runner.temp }}/.kube/kubeconfig_${{ github.job }}" apply -f "${{ inputs.DEPLOYMENT_FILE }}"
        rm "${{ runner.temp }}/.kube/kubeconfig_${{ github.job }}"

    - name: "Run post script"
      shell: bash
      run: if test -f "${{ inputs.CICD_DIR }}/post_deployment.sh"; then bash "${{ inputs.CICD_DIR }}/post_deployment.sh" ${{ inputs.PARAM_POSTSCRIPT }}; fi
